"""
Automation Engine (AAL Evaluator)
─────────────────────────────────
Parses and evaluates Artemis Automation Language (AAL) rules.
Example: WHEN temperature > 28 IF somebody_home == true THEN turn on the fan.
"""

from typing import Dict, Any
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.models import Automation, User
from app.services import hardware_service

class AutomationTrigger:
    def __init__(self, key: str, operator: str, value: float | str):
        self.key = key
        self.operator = operator
        self.value = value

def parse_aal(rule_text: str) -> dict:
    """
    Very basic string-matching parser for AAL.
    In a production system, use a tokenizer or AST parser.
    """
    rule = rule_text.lower()
    
    # Defaults
    parsed = {
        "trigger": None,
        "condition": None,
        "action": None,
        "silent": False
    }

    if "when " in rule:
        parts = rule.split("when ")[1].split(" then ")
        if len(parts) == 2:
            trigger_part = parts[0]
            action_part = parts[1]

            if " if " in trigger_part:
                t_split = trigger_part.split(" if ")
                parsed["trigger"] = t_split[0].strip()
                parsed["condition"] = t_split[1].strip()
            else:
                parsed["trigger"] = trigger_part.strip()
            
            parsed["action"] = action_part.strip()
            
            if parsed["action"].startswith("silently "):
                parsed["silent"] = True
                parsed["action"] = parsed["action"].replace("silently ", "")

    return parsed

async def evaluate_rules(db: AsyncSession, current_context: Dict[str, Any]):
    """
    Evaluates all active automations against the current context.
    Context should include recent sensor readings and time.
    """
    # Fetch active rules
    result = await db.execute(select(Automation).where(Automation.is_enabled == True))
    automations = result.scalars().all()

    for auto in automations:
        rule_def = parse_aal(f"WHEN {auto.trigger} IF {auto.condition or 'true'} THEN {auto.action}")
        
        # Super simplified evaluation, e.g. "temperature > 28"
        t_str = rule_def.get("trigger", "")
        # e.g. "temperature > 28"
        is_triggered = _evaluate_expression(t_str, current_context)
        
        c_str = rule_def.get("condition", "true")
        is_conditioned = True if c_str == "true" else _evaluate_expression(c_str, current_context)

        if is_triggered and is_conditioned:
            await _execute_action(auto, rule_def, current_context, db)


def _evaluate_expression(expr: str, context: dict) -> bool:
    """Evaluates simple expressions like 'temperature > 28'."""
    # This is a stub for safety. Ideally parse operator safely.
    if ">" in expr:
        key, val = [x.strip() for x in expr.split(">")]
        sensor_val = context.get(key)
        if sensor_val is not None:
            try:
                return float(sensor_val) > float(val)
            except ValueError:
                pass
    elif "<" in expr:
        key, val = [x.strip() for x in expr.split("<")]
        sensor_val = context.get(key)
        if sensor_val is not None:
            try:
                return float(sensor_val) < float(val)
            except ValueError:
                pass
    elif "==" in expr:
         # etc...
         pass

    return False


async def _execute_action(automation: Automation, rule_def: dict, context: dict, db: AsyncSession):
    """
    Executes the action or dispatches a proactive notification to the user.
    """
    action = rule_def["action"]
    
    if rule_def["silent"]:
        # Execute directly via hardware service
        # Parse basic device commands like "turn on fan"
        device = "unknown"
        act = "on"
        if "fan" in action:
            device = "fan"
        if "off" in action:
            act = "off"
            
        try:
            await hardware_service.send_command(device, act)
            print(f"Executed AAL Action (silent): {device} -> {act}")
        except Exception as e:
            print(f"Failed AAL execution: {e}")
            
    else:
        # Require proactive user approval
        # (This is where WebSockets / Server-Sent-Events shine to PUSH to the app)
        print(f"Proactive Suggestion generated by AAL: {automation.name} -> Would you like to {action}?")
        # Push notification logic would go here.
